import Head from 'next/head';
import Banner from './components/Banner';
import Header from './components/Header';
import ProductFeed from './components/ProductFeed';




export default function Home({ products }) {
  return (
    <div >
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/d/de/Amazon_icon.png" />
      </Head>
         <Header/>
      <main className='max-w-screen-2xl mx-auto'>
        <Banner/>
        <ProductFeed products={products} />
        
      </main>

      <footer>
       
      </footer>
    </div>
  )
}

export async function getServerSideProps(context){
  const products = await fetch("https://secret-brushlands-54492.herokuapp.com/allproducts").then(
    res => res.json()
  );
  return{
    props:{
      products:products,
    }
  }
}
